### ISSUE TITLE
Customize keyboard shortcuts

### ISSUE THREAD

**Issue by xHN35RQ** [craigbarnes/showdown#10]
Or at least offer vim-friendly keybinds?

**Comment by craigbarnes** [comment]
There will eventually be a preferences dialog hooked up to `GSettings`, so I guess custom key bindings could be a part of that.

**Comment by xHN35RQ** [comment]
Meh, not useful enough in my opinion. Thoughts? I opt to close on account of feature creep.

**Comment by xHN35RQ** [comment]
Closing because Gnome apps should probably follow standard desktop environment keybindings. No need to deviate from that.
