### ISSUE TITLE
Watch directory and auto-load any recently changed documents

### ISSUE THREAD

**Issue by xHN35RQ** [craigbarnes/showdown#11]
Allow to open a directory with Showdown, watch the entire directory for any changed `.md` or `.txt` files and auto-load into the viewer.

**Comment by xHN35RQ** [comment]
To elaborate a bit: It's handy to watch an entire directory if you're working with multiple Markdown documents, this way Showdown displays the most recently changed Markdown file at all times... becoming an 'intelligent assistant' of sorts. Simply by editing and saving files, those files are magically updated into Showdown without requiring action from the user.

This is somewhat related to [my comment here](https://github.com/craigbarnes/showdown/issues/22#issuecomment-138214140) because if Showdown is able to load files to the same window instead of spawning new windows... then I can setup my own directory watcher (for example using python inotify) and can push the most recently changed files to Showdown.

But I think in the long run it would be easier for the user to have Showdown be able to watch entire folders. I'm not sure how much more difficult this would be to code than a single file watcher.

**Comment by craigbarnes** [comment]
The idea I had for a general 'open directory' feature was to show all the markdown files in a given directory in a (hideable) sidebar, similar to gedit. This could then have a "show most recent edit" option, that would monitor the whole directory and select the most recently edited file in the sidebar and load it into view.

I don't really want to add features without making them sufficiently general purpose and suitable for various potential use cases, so it would be quite a bit of effort to implement the whole thing.

**Comment by xHN35RQ** [comment]
Sure, I see what you mean. This sidebar idea seems a good general purpose approach. And my use case of watching an entire directory is solved by your suggested option of `--reuse-window` because I can implement my own dir watchers in python.

So... I'm closing this because the requested feature is off-tangent from your design goals, and your side-bar/drawer feature should have it's own issue.

**Comment by craigbarnes** [comment]
I've added a basic directory watcher in 2d810672. Pull requests/suggestions welcome.

**Comment by xHN35RQ** [comment]
Wow that's really cool, it works very well. Thanks for adding it! :trophy: :trophy: :trophy:
