### ISSUE TITLE
Allow to set multiple file types

### ISSUE THREAD

**Issue by xHN35RQ** [craigbarnes/showdown#12]
Default to `.md` and `.markdown` perhaps add others?

* .text
* .mdown
* .mkdn
* .mkd
* .mdwn
* .mdtxt
* .mdtext

**Comment by craigbarnes** [comment]
Do you mean for the "Markdown files" filter in the open dialog? If so, it currently just shows anything the system MIME database recognizes as `text/x-markdown` (currently `*.md`, `*.markdown` and `*.mkd` files on my system). It is possible to add specific extensions but I think it'd be better to just add your list to the MIME database (either upstream or manually).

**Comment by xHN35RQ** [comment]
That makes sense. My list was excessive. Sometimes I use `.txt` with markdown inside, and I'm aware a lot of other people do as well, so perhaps just adding `text/plain` somewhere in there?

**Comment by craigbarnes** [comment]
I'm going to close this. The existing `All Files` filter can show `text/plain` files. Any missing and reasonable extensions should be added to the upstream MIME database. FWIW, I think `.txt` is too ambiguous and should just be avoided.

**Comment by xHN35RQ** [comment]
cool thanks.
