### ISSUE TITLE
[enhancement] Local links between documents should load the linked document

### ISSUE THREAD

**Issue by xHN35RQ** [craigbarnes/showdown#13]
Allow user to link documents together locally. Given a link in the current document to a local Markdown document, load in the new document into Showdown when user clicks the link.

**Comment by craigbarnes** [comment]
I've started hacking on this a little. It either needs a `WebKitPlugin` that handles `text/x-markdown` documents or some kind of hook in the [WebView::decide-policy](http://webkitgtk.org/reference/webkit2gtk/unstable/WebKitWebView.html#WebKitWebView-decide-policy) signal.

**Comment by craigbarnes** [comment]
Fixed in e1f424d0.

**Comment by xHN35RQ** [comment]
great thanks!
