### ISSUE TITLE
Best way to check for GTK+ version?

### ISSUE THREAD

**Issue by xHN35RQ** [craigbarnes/showdown#14]
I guess Vala doesn't offer compilation conditionals so you can't check for GTK+ version from within the Vala code. I don't know of a way to make a single executable that works for both GTK+ 3.12 and 3.10.

But you can check for GTK+ version in Makefile, and use and if-then loop to compile different sources.

So - that means that you can have something like `showdown.vala` for GTK+ 3.12 and up, and `showdown-gtk3.10.vala` for older GTK+ versions that includes the older API calls.

Then in Makefile you set the proper if-then switch to choose the right vala file to compile.

Sorry if this is old hat to you, I've never used Vala so I'm thinking out loud here. Thanks.

**Comment by craigbarnes** [comment]
To be honest, I've also never used Vala until a few hours ago, so I'm not sure either. From searching around a little, it seems Vala does have a limited form of conditional compilation, but I don't know if it's the correct way to handle this. I'll look into it more when I've finished the basic porting work.

**Comment by craigbarnes** [comment]
Just for context, for anyone else reading: https://github.com/craigbarnes/showdown/blob/f05605e26a3be34258f0bd3ab6616319a1eda00e/showdown.vala#L192-L193

**Comment by craigbarnes** [comment]
I've just pushed a [commit](https://github.com/craigbarnes/showdown/commit/13800761f823fcd2df874a5fb6cfb9589ca81728) that should fix compilation with pre-3.12 versions of GTK. Testing/feedback welcome.

**Comment by xHN35RQ** [comment]
Bingo! Works great! I have some build errors though:

https://gist.github.com/xHN35RQ/a20a3ff3f4d587000199

**Comment by xHN35RQ** [comment]
Closing since compiling `showdown` on 3.10 works perfectly.
