### ISSUE TITLE
Invisible dead space surrounding Showdown window

### ISSUE THREAD

**Issue by xHN35RQ** [craigbarnes/showdown#16]
The window seems to have an odd invisible dead space of 30-40 pixels surrounding the entire window. This space blocks the cursor from interacting with windows & content behind the Showdown window.

**Comment by craigbarnes** [comment]
I just get the window resize cursor if I hover up to about 30 pixels from the edge; but I get the same for every other window too. Does it only happen with this one app? I guess I'll have to fire up a Ubuntu VM and see if I can reproduce.

**Comment by xHN35RQ** [comment]
It happens with just this app, perhaps it's due to the "chrome-less" aspect of the window? It's as if the window bounding region extends beyond the window for some reason.

**Comment by xHN35RQ** [comment]
no longer a problem on ubuntu 15.04. it must have been an issue with cinnamon which i was using before.
