### ISSUE TITLE
Merge vala branch

### ISSUE THREAD

**Issue by craigbarnes** [craigbarnes/showdown#17]
The following items need to be implemented before the `vala` branch can be merged into `master`:

* [x] ~~Create libcmark Vala bindings (c4d2f7be)~~
* [ ] ~~Create a table-of-contents serializer for libcmark~~
* [x] Create libmarkdown Vala bindings (cbaf54dd)
* [x] Loading user stylesheet from `$XDG_CONFIG_HOME/showdown/stylesheet.css` (177a8a15)
* [x] Update `README.md` (particularly the installation and requirements sections)
* [x] Enable `DOCUMENT_VIEWER` cache model with `WebKitWebContext::set_cache_model`
* [x] Disable JavaScript, plugins and page cache via `WebKitSettings`

**Comment by xHN35RQ** [comment]
I can't think of anything else to get `vala` up to `master` - I'm assuming you'll work on my pull request items after you get the branches equal.

**Comment by craigbarnes** [comment]
> `vala` window launches much wider, and shorter than `lua` and I'm not sure why.

This should be fixed as of commit [8356e5a](https://github.com/craigbarnes/showdown/commit/8356e5a3afa0bd9b072d17eb9d535c8181088cd1).

> I'm assuming you'll work on my pull request items after you get the branches equal.

That's the idea, yeah. I'm a little stuck on implementing the table of contents feature at the moment though. Neither Pandoc nor cmark have a straight forward way to generate a table of contents like Discount does.

> Also, is it supposed to load external URLs in-window? I'd have thought those would be pushed out to default system browser.

Yeah, I agree. For now it's just using the default behaviour of the WebKit view but the `WebView::decide-policy` hook (also mentioned in #13) could be used to forward external links to the default browser. I'll probably work on this at the same time as #13.

**Comment by xHN35RQ** [comment]
> This should be fixed as of commit 8356e5a.

Thanks.

>  Neither Pandoc nor cmark have a straight forward way to generate a table of contents like Discount does.

Pandoc offers `--toc` and `--toc-depth`. Do these options not offer enough flexibility? I'll try testing this out when I get a chance to see how pandoc outputs Table of Contents.

**Comment by craigbarnes** [comment]
Just updated the todo list.

**Comment by craigbarnes** [comment]
Turns out writing a ToC serializer for libcmark is not as simple as I thought (jgm/cmark#78). I started to implement one here, but it's looking like it'll be better to submit it upstream and wait for the next cmark release.

In the meantime, the `vala` branch is already using the libcmark API. Any testing/feedback welcome.

It's probably worth mentioning that cmark doesn't yet support Markdown Extra style tables, including [the one in the Showdown readme](https://github.com/craigbarnes/showdown#keyboard-commands).

**Comment by craigbarnes** [comment]
I've decided to go back to using Discount/libmarkdown instead of cmark for now. Using cmark will require too much extra work and has too many feature regressions to use for now. Discount is also much more widely packaged.

@xHN35RQ

I've also updated the readme. Hopefully the [installation section](https://github.com/craigbarnes/showdown/tree/cbaf54dd01b1c1fb1b0b3a274b8da2b1404baa97#installation) is more useful than before.

**Comment by craigbarnes** [comment]
Merged.

**Comment by xHN35RQ** [comment]
> I've also updated README.md. Hopefully the installation section is more useful than before.

Yep! Very helpful. Thanks.

**Comment by xHN35RQ** [comment]
> I've decided to use Discount/libmarkdown instead of cmark for now. Using cmark requires too much extra work and causes too many feature regressions. It also isn't packaged by any mainstream distro yet.

Is there an option to use pandoc instead Discount? I'd rather use pandoc.

**Comment by craigbarnes** [comment]
> Is there an option to use pandoc instead of Discount?

Not at the moment, but I may implement it at some point.

**Comment by xHN35RQ** [comment]
It's working fine for me using just libmarkdown, i didn't need to build Discount at all.

**Comment by craigbarnes** [comment]
libmarkdown is the name of the Discount library ;). I guess using the two interchangeably is confusing.

**Comment by xHN35RQ** [comment]
> libmarkdown is the name of the Discount library ;)

I guessed as much. Good to know!! :smile:
