### ISSUE TITLE
Add rockspec

### ISSUE THREAD

**Issue by daurnimator** [craigbarnes/showdown#19]
It'd be nice to install via luarocks.

**Comment by xHN35RQ** [comment]
@craigbarnes is actually working on porting this to Vala, so eventually I imagine this could be packaged up for different distros.

**Comment by craigbarnes** [comment]
The `vala` branch has now been merged into `master`, so luarocks packaging is kind of obsolete now. I plan on packaging Showdown for at least Fedora and Arch at some point.
