### ISSUE TITLE
Restore scroll position after reloading

### ISSUE THREAD

**Issue by craigbarnes** [craigbarnes/showdown#2]

**Comment by craigbarnes** [comment]
This is [ridiculously complicated](http://stackoverflow.com/questions/21781868/scrolling-a-webkit2-webkit-window-in-gtk3#answer-21866372) to do via the WebKit2Gtk API.

**Comment by xHN35RQ** [comment]
Jump to newest change would be nice. This keeps the document auto-scrolled to the current location being edited.
