### ISSUE TITLE
Zooming

### ISSUE THREAD

**Issue by daurnimator** [craigbarnes/showdown#20]
I've got a high DPI 4k screen where showdown text is too small to read.
Can you add a zooming capability?

**Comment by craigbarnes** [comment]
I guess zooming would be a good addition, but it'd be nice to work by default on 4k screens. Maybe the stylesheet could accommodate this somehow. I'll look into it when I get time, although I currently don't have a 4k screen to test on.

**Comment by craigbarnes** [comment]
Not having a 4K screen to test on is kind of a blocker for me on this one. If you can suggest any changes to the stylesheet to fix font scaling, I'd gladly merge them. I will also add zooming at some point, but I'm not sure it's the ideal fix for this.

**Comment by craigbarnes** [comment]
Just added some accelerator keys for zooming the webview (`<ctrl>+`, `<ctrl>-` and `<ctrl>0`).

**Comment by daurnimator** [comment]
Great, that works :)
