### ISSUE TITLE
Load non-markdown links in external browser

### ISSUE THREAD

**Issue by craigbarnes** [craigbarnes/showdown#21]
As [mentioned](https://github.com/craigbarnes/showdown/issues/17#issuecomment-129404111) in #17, links to external HTML documents are currently loaded within the Showdown window, but since Showdown is specifically a Markdown viewer, these links should really be forwarded to the default browser. The best way to accomplish this appears to be via the `WebView::decide-policy` signal.

**Comment by craigbarnes** [comment]
Done, as part of e1f424d0.

**Comment by xHN35RQ** [comment]
awesome to see all these updates. thanks!!
