### ISSUE TITLE
Automatically reload when the source document changes

### ISSUE THREAD

**Issue by craigbarnes** [craigbarnes/showdown#22]
This is somewhat related to #11, but not exactly the same.

**Comment by xHN35RQ** [comment]
Is there a way to tell Showdown to load a new document in the current window? Say, from the command line, if I launch `showdown file.md` is there a way for Showdown to check for existing window and load the file into that instead of launching a new one.

**Comment by craigbarnes** [comment]
I could add a command-line flag that makes the app reuse the most recently opened window, e.g. something like `showdown --reuse-window file.md`. Would that work?

**Comment by xHN35RQ** [comment]
That would be perfect! Thanks.

**Comment by craigbarnes** [comment]
Done in d1d3eeeb. You can now use `showdown -w FILENAME`. If Showdown is already running, it'll open `FILENAME` in the currently focused window, otherwise it'll open a new window. Let me know if you need anything else.

**Comment by xHN35RQ** [comment]
Yeah, `-w` works nicely now! However this issue title is "Automatically reload when the source document changes" - I'm sorry I derailed the issue with my request. :stuck_out_tongue:

**Comment by craigbarnes** [comment]
Haha, no problem. I should have checked the title before I closed it.
