### ISSUE TITLE
Add back/forward navigation buttons to the headerbar

### ISSUE THREAD

**Issue by craigbarnes** [craigbarnes/showdown#23]
This is definitely needed, now that linking between local documents is working correctly.

**Comment by xHN35RQ** [comment]
perhaps consider keybinds for forward and back as well.

**Comment by craigbarnes** [comment]
> Perhaps consider keybinds for forward and back as well.

Yep, I'll add accelerator keys for both.

> Also right now when I click a link to a local document, it opens in new window, so are nav buttons needed?

Hmm, that's not working as expected then. Could you give some example filenames? What do you get if you run:

    xdg-mime query filetype FILENAME
