### ISSUE TITLE
libwebkit2gtk-4.0-dev is required to build on ubuntu

### ISSUE THREAD

**Issue by xHN35RQ** [craigbarnes/showdown#24]
should be 

`sudo apt-get -y install valac gcc make gir1.2-webkit2-4.0 libwebkit2gtk-4.0-dev libmarkdown2-dev`

**Comment by craigbarnes** [comment]
Thanks for the heads up. Should be fixed in 8da96521 (I dropped the `gir1.2-webkit2-4.0` part, since it should be pulled in by `libwebkit2gtk-4.0-dev`).
