### ISSUE TITLE
table of contents displays (null) when there is no level 1 header

### ISSUE THREAD

**Issue by xHN35RQ** [craigbarnes/showdown#25]
If there is no level 1 header, ToC perhaps can just be blank and not show (null)... or perhaps disappear entirely. Thanks!

**Comment by craigbarnes** [comment]
I've pushed a quick fix as ecfefd1a. I'll leave this issue open until the [todo](https://github.com/craigbarnes/showdown/commit/ecfefd1ad18174cb5ae3fe645f39b809bee731cf#diff-5be53a9aea8a4199daa4814b19b4262fR165) from that commit is also done.

**Comment by xHN35RQ** [comment]
ok thanks

**Comment by craigbarnes** [comment]
Fixed in ed947f0324abb6d8a1c4608aa1d39c543853bc8f.

**Comment by xHN35RQ** [comment]
Perfecto! Thanks for the fix. One thing I noticed on documents without ToC is that the documents are 100% width of the Showdown window. It might be nice to have a max-width? Maybe 80-90 char?

**Comment by craigbarnes** [comment]
Yeah, the stylesheet definitely needs a few tweaks. High DPI text scaling also needs to be fixed. I'll get around to it, but probably not for a few days.

**Comment by xHN35RQ** [comment]
I actually started working on some tweaks, but didn't know your goals for the stylesheet. Would you like to imit max-width to a specific number of characters per line?

**Comment by craigbarnes** [comment]
> Would you like to imit max-width to a specific number of characters per line?

Yeah, I think it should be limited to around 80 characters or so. I'm not sure about the best way to do it though. Should the font size scale up with the window size? Or should the content be centred and just have growing space either side, once the limit is reached? I haven't given it much thought yet, but help is definitely welcome.

**Comment by xHN35RQ** [comment]
Ok I'll put a pull request together so you can see what I'm thinking.
