### ISSUE TITLE
Links to local Markdown documents open in a new window instead of the current window

### ISSUE THREAD

**Issue by craigbarnes** [craigbarnes/showdown#26]
As originally [reported](https://github.com/craigbarnes/showdown/issues/23#issuecomment-138039252) by @xHN35RQ in #23:
    
>> Also right now when I click a link to a local document, it opens in new window ...

> Hmm, that's not working as expected then. Could you give some example filenames? What do you get if you run `xdg-mime query filetype FILENAME`?

**Comment by craigbarnes** [comment]
This may be fixed by b254dac, but possibly not...

**Comment by xHN35RQ** [comment]
Fixed! It works well to link between documents. Awesome! :+1: Fixed! It works well to link between documents. Awesome! :+1:

**Comment by craigbarnes** [comment]
Cool, thanks for testing!
