### ISSUE TITLE
Showdown tries to open files relative to ~/

### ISSUE THREAD

**Issue by xHN35RQ** [craigbarnes/showdown#30]
If I launch Showdown from .desktop launcher, and if in command line I'm in a subfolder of `~/` for example `Documents` and I try to open a document from command line in same folder for example `showdown file.md` Showdown tells me `Unable to open document: "file:///home/nic/Documents/file.md" File doesn't exist` which of course it doesn't exist in `~/`.

So command line showdown needs to fully expand file paths of files passed on the command line, or somehow needs to navigate to current folder of execution before attempting to open file. Hope that's enough information! Thanks.

**Comment by craigbarnes** [comment]
Should be fixed by e2b3fead. Thanks for the report!

**Comment by xHN35RQ** [comment]
Perfecto. Thanks for the fix.
