### ISSUE TITLE
Switch to GtkBuilder templates for window layout

### ISSUE THREAD

**Issue by craigbarnes** [craigbarnes/showdown#33]
Using [composite templates](https://blogs.gnome.org/tvb/2013/05/29/composite-templates-lands-in-vala/) and [`GResource`](http://valadoc.org/#!api=gio-2.0/GLib.Resource) in `window.vala` would clean up a lot of boilerplate code.

**Comment by craigbarnes** [comment]
I've [bumped](https://github.com/craigbarnes/showdown/commit/c5654a021c514caccb2c908676f26f604d77fa31) the minimum required library versions in preparation for this, which means no more support for Ubuntu 14.04.

**Comment by xHN35RQ** [comment]
Unless someone wants to put 3.14 on their 14.04 release, which as I understand isn't that hard to do.

**Comment by craigbarnes** [comment]
Done in f819f968.
