### ISSUE TITLE
Syntax highlighting for code blocks

### ISSUE THREAD

**Issue by craigbarnes** [craigbarnes/showdown#34]
Discount doesn't offer any way to post-process code blocks, but we could inject a JavaScript syntax highlighter via the page template (or via `WebKit.UserContentManager.add_script()`).

**Comment by craigbarnes** [comment]
Hopefully it's possible to enable user scripts somehow without allowing JavaScript on the page, since Markdown can pass through `<script>` blocks and `javascript:` URIs.

**Comment by xHN35RQ** [comment]
Maybe https://highlightjs.org?

**Comment by xHN35RQ** [comment]
Or perhaps http://prismjs.com - [possibly relevant discussion](https://github.com/sindresorhus/github-markdown-css/issues/18)

**Comment by craigbarnes** [comment]
I hacked around with this idea a while back. Unfortunately, it doesn't seem possible to add a script without also enabling JavaScript on the page (which is out of the question for Showdown).

**Comment by craigbarnes** [comment]
I've changed my mind about this. Enabling JavaScript on the page should be fine so long as the Markdown parser is configured properly. After issue #37 is closed, I'll look into adding a syntax highlighter script. I'd very much prefer to use one that does proper parsing (as opposed to regex matching), but I'm not sure such a thing exists in JavaScript...?

**Comment by vidhya03** [comment]
+1

**Comment by craigbarnes** [comment]
I've just [added](babeb500971920fd1b6016c025c7937938a97061) support for loading a user script from `~/.config/showdown/script.js`, which can be used to add a syntax highlighting script of your choice. User styles can be added to `~/.config/showdown/stylesheet.css`.

I've also tested using highlightjs via this method and it all seems to work as expected.

**Comment by craigbarnes** [comment]
I've been procrastinating about adding built-in syntax highlighting because I can't make up my mind which one to use. Is support for user scripts enough or should a specific JS library be provided and enabled by default?

**Comment by craigbarnes** [comment]
Moved to https://gitlab.com/craigbarnes/showdown/issues/34
