### ISSUE TITLE
Deb (Or PPA) for easy installation on Ubuntu/Debian?

### ISSUE THREAD

**Issue by khurshid-alam** [craigbarnes/showdown#38]
It would be nice to have deb (Or PPA) for Ubuntu and Debian based distros.

Thanks.

**Comment by craigbarnes** [comment]
Packaging for Debian requires a Debian host system and also someone interested in maintaining the package long term. If there's a Debian user out there who would like to maintain a package for Showdown, I'd be glad to assist however I can as upstream, but I'm afraid I won't be doing the packaging work myself.

The alternative is either to compile the traditional way or install the flatpak app using the command:

    flatpak install https://craigbarnes.gitlab.io/showdown/showdown.flatpakref

I think flatpak is available in Debian testing and also Debian Jessie backports. If you don't want to install as root, it's also possible to install the flatpak for just the current user:

    flatpak install --user https://craigbarnes.gitlab.io/showdown/showdown.flatpakref
