### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by craigbarnes** [craigbarnes/showdown#48]
* [ ] Move "refresh" item from the menu to a HeaderBar button...?
* [ ] Add zoom controls to the menu...?
* [ ] Add next/prev buttons to the search bar.

**Comment by sebastiaanfranken** [comment]
For the refresh button you could bundle that with the search button in a Gtk Box (with style class 'linked') containing a Gtk Image 'view-refresh-symbolic' perhaps?

**Comment by craigbarnes** [comment]
Moved to https://gitlab.com/craigbarnes/showdown/issues/31
