### ISSUE TITLE
[Feature Request] Separate scrollbar for the 'Table of contents navigation'

### ISSUE THREAD

**Issue by tnilzon** [craigbarnes/showdown#51]
It would be great with a separate scrollbar for the 'Table of contents navigation' field. That would make it easier to navigate in a document and to select new items in the 'Table of contents' without the need to always scroll to the top.

**Comment by craigbarnes** [comment]
I've been thinking about this for a while. The quick solution would be to just change the HTML template to use a scrolling sidebar.

Another solution would be to use a scrolling GTK widget for the table-of-contents, although that would require a Markdown parser with full control over rendering (#37).

I'm busy with other thing at the moment, but I'll come back to this issue eventually.

**Comment by tnilzon** [comment]
Great, thanks!

**Comment by craigbarnes** [comment]
Issue moved to the GitLab [issue tracker](https://gitlab.com/craigbarnes/showdown/issues/39) (the GitHub repo is just a secondary mirror).
