### ISSUE TITLE
Add support for images in local directory

### ISSUE THREAD

**Issue by xHN35RQ** [craigbarnes/showdown#6]
Given `file.md` and `image.jpg` upon embedding `![](image.jpg)` in `file.md` there is no image displayed in showdown. Even given a full path `![](/home/user/Desktop/image.jpg)` there is no image displayed.

It would be perfect to have support for images in current directory of `file.md` and sub-directories relative to the current file such as:

    ![](image.jpg)
    ![](images/1.jpg)
    ![](images/more_images/2.jpg)

**Comment by craigbarnes** [comment]
This should be fixed in the `vala` branch.

**Comment by xHN35RQ** [comment]
Not in as of 13800761f8

**Comment by xHN35RQ** [comment]
Here's my current build errors: https://gist.github.com/xHN35RQ/a20a3ff3f4d587000199

**Comment by craigbarnes** [comment]
Oops, yeah I spoke a bit prematurely here. The Markdown->HTML conversion hasn't been implemented in the `vala` branch at all yet -- I've just been testing by loading HTML files directly.

What I should have said is that `WebView::base_uri` is being set correctly in the `vala` branch, so it should work as expected as soon as Markdown -> HTML rendering is implemented.

**Comment by craigbarnes** [comment]
> Here's my current build errors: https://gist.github.com/xHN35RQ/a20a3ff3f4d587000199

Those are both warnings rather than errors. You should still have a `showdown` executable produced. I also get those 2 warnings, but I think they're bugs in the Vala code generator or .vapi bindings.

**Comment by xHN35RQ** [comment]
Ah yes they are warnings, yes the executable is building nicely.

And loading an HTML directly works great! The local images work great.

**Comment by xHN35RQ** [comment]
Closing because this is nicely fixed in `vala` branch.

**Comment by xHN35RQ** [comment]
Closing because this is nicely fixed in `vala` branch.
