### ISSUE TITLE
Menu option to select custom CSS styles

### ISSUE THREAD

**Issue by xHN35RQ** [craigbarnes/showdown#7]
- [ ] Add option to select from different CSS styles.
- [ ] Auto-refresh document upon selection of new style.
- [ ] Watch local folder and display any `.css` files in that folder as selectable on the menu. ([here's one way of doing this](https://github.com/mborgerson/MarkdownViewer/blob/master/MarkdownViewer.py#L46-#L60))

- [ ] Add option to select no-ToC stylesheet?

**Comment by craigbarnes** [comment]
This seems reasonable. The app could load a list of all `*.css` files under `~/.config/showdown/styles/` at startup and show them in a `GtkPopover`. The [current way](https://github.com/craigbarnes/showdown/blob/177a8a155da27851a1a6ea498d75405411a03f76/showdown.vala#L205) of handling custom user stylesheets could be replaced by making `~/.config/showdown/styles/default.css` the default.

**Comment by xHN35RQ** [comment]
This also feels a little like feature creep. It's useful, but is it useful enough?
