### ISSUE TITLE
Toggle ToC

### ISSUE THREAD

**Issue by xHN35RQ** [craigbarnes/showdown#8]
Allow ToC to be toggle-able. This is probably as simple as selecting a new CSS style. See #7.

**Comment by craigbarnes** [comment]
I'll definitely add this at some point. I've just been thinking of the best way to add and remove styles without incurring a full reload (which would also mean losing the current scroll position).

**Comment by xHN35RQ** [comment]
I think it's simpler to have an alternate CSS style marked as no-ToC. If so I'll close this.

**Comment by xHN35RQ** [comment]
Actually I'm closing this because I've come to believe ToC are super-helpful. No need to add this feature until someone asks for it specifically.

**Comment by xHN35RQ** [comment]
Let me know if I'm closing too aggressively, however I realized that most of the issues I'd opened on this project are non-essential functionality and there's no reason for you to build a feature that hardly anyone will use.
