### ISSUE TITLE
Add Export & Print options

### ISSUE THREAD

**Issue by xHN35RQ** [craigbarnes/showdown#9]
GTK+ offers a native print dialog for sending to a physical printer, however any HTML or PDF exports should be handled by the markdown processor. (i.e. libcmark)

Perhaps to start with, ignore GTK+ printing and just let the user figure out how to print from the files that are exported.

Assume some basic defaults at first (export to Desktop) and in future builds allow for setting custom export locations, and perhaps export settings (paper size, layout orientation, etc.)

**Comment by craigbarnes** [comment]
WebKit has a built in [PrintOperation](http://valadoc.org/#!api=webkit2gtk-4.0/WebKit.PrintOperation) class for this. It shouldn't be too hard to hook up the basics.

**Comment by craigbarnes** [comment]
I've added basic printing in 1f6180cc. I'm not sure whether to hide the ToC or not yet. The "Print to File" option should handle PDF exports.

**Comment by xHN35RQ** [comment]
> I'm not sure whether to hide the ToC or not yet.

I vote to print what the user sees... so the user can either toggle the ToC by switching to another stylesheet, or perhaps add a setting to toggle ToC on any given stylesheet.

**Comment by xHN35RQ** [comment]
It prints nicely to printer and PDF. Works well! :+1:
